sequenceDiagram
    loop One-Way Data Flow
        participant CA as Apollo Cache
        participant UI as <create-network>
        participant OL as <select-item>
        CA->>UI: AllSitesQuery
        UI-->>OL: Property Assignment
        OL->>UI: Select Event
        UI-->>CA: writeFragment
    end
