[build]
  publish = "_site/"


[[redirects]]
  from = "/modules/_apollo_elements_haunted.html"
  to = "/api/libraries/haunted/"
[[redirects]]
  from = "/modules/_apollo_elements_components.html"
  to = "/api/components/"
[[redirects]]
  from = "/pages/Guides/getting-started.html"
  to = "/guides/getting-started/"
[[redirects]]
  from = "/pages/Guides/migrating.html"
  to = "/guides/getting-started/migrating/"
[[redirects]]
  from = "/pages/Using%20Apollo/local-state.html"
  to = "/guides/building-apps/local-state/"
[[redirects]]
  from = "/pages/Using%20Apollo/mutations.html"
  to = "/guides/building-apps/mutations/"
[[redirects]]
  from = "/pages/Using%20Apollo/queries.html"
  to = "/guides/building-apps/queries/"
[[redirects]]
  from = "/pages/Using%20Apollo/subscriptions.html"
  to = "/guides/building-apps/subscriptions/"
[[redirects]]
  from = "/pages/using%20apollo/queries"
  to = "/guides/building-apps/queries/"

[[plugins]]
package = "netlify-plugin-a11y"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]

  resultMode = "warn" # is "error" by default
