name: Validate PR

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.3
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: c-hive/gha-npm-cache@v1

      - name: Install Dependencies
        run: npm ci

      - name: Codegen
        run: npm run build:codegen

      - name: Check Types
        run: npm run lint:types

      - name: Test
        run: npm run test

      - name: Publish Code Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  build:
    name: Build Dry-Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: c-hive/gha-npm-cache@v1

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

  docs:
    name: Build and Check Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: c-hive/gha-npm-cache@v1

      - name: Install Dependencies
        run: npm ci

      - name: Build Docs
        run: npm run docs
