name: Validate PR

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Codegen
        run: npm run build:codegen

      - name: Lint
        run: npm run lint

      - name: Test
        run: |
          npm test -- --coverage
          npm test --prefix packages/create

      - name: Publish Code Coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CLEAN_MVN_REPO }}
        if: env.CC_TEST_REPORTER_ID != null
        uses: paambaati/codeclimate-action@v3.0.0

      - name: Build
        run: npm run build
