name: Validate PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - uses: hallee/eslint-action@1.0.3
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: yarn install

      - name: Codegen
        run: yarn build:codegen

      - name: Check Types
        run: yarn lint:types

      - name: Test
        run: yarn test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: yarn build
