name: Validate PR

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.3
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install Dependencies
        run: sudo yarn --frozen-lockfile

      - name: Codegen
        run: yarn build:codegen

      - name: Check Types
        run: yarn lint:types

      - name: Test
        # HACK: temporarily disable testing of hybrids files - they pass locally but timeout in CI.
        run: yarn test --files 'packages/!(hybrids)/*.test.ts'

      - name: Test & Publish Code Coverage
        uses: paambaati/codeclimate-action@v2.7.3
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  build:
    name: 'Build Dry-Run'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install Dependencies
        run: sudo yarn --frozen-lockfile

      - name: Build
        run: yarn build

  docs:
    name: 'Build and Check Docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install Dependencies
        run: sudo yarn --frozen-lockfile

      - name: Build Docs
        run: yarn docs
